language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

after_success:
  - curl https://bodoni.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: ykRSe7/34if243VRsDgwXWEHx3gswICOjL5J6OjWysUCV67i7Nr3ftPiOhoJY5xHCvd622LNZnflWE+CX7Oft992xNYVr7j9F5PGDdsMrBU/TBxxdEMFvkXZgwcJ2/kqwOkbTcgbkZo7ZyPwm3L5duWTmHh36s0xtG1/n6zuDuRQFEq68a8S0heHX4O62I7ONkL+NoW5pdQpJCdeJn50UV0jbbcMv3Ab/3eub//YfgyJXj8E7R4ZbmUGUieX0Y3kgGJ+Tz+9dAfyqrr1OnX7Sh5XmvMxj/aHkU2n39Jhhk3SmXobGm9jzFLIl6gQFNMOHcyqEiIOw7ZvoR+Sj5Fs773b4WVBfzgSqS0shzr5PVrmgcqwmZqSDVsF1qafaR2HumCCyPJSP3unqjFkq0bZOljyNyM8HXUTwntdIXop9Z1gnxRrj/VS+skYvowKbEzw6Pgi7USnuOkqXwnaiFilgE+fJq9e7ZnPl2Mh9bdvhpVz8R9KSho1MiS/5kU55PTTr+JGLn840KwrnJWmZY5oQ85+THhP6qekzo4j4N5m7kkNOh+QajOwvZaG3cnQcuAdtgt9uoL0kDWBnKpvE0g3ZrufjGtjCmYPzitT1cxwSDxSG+b9rsGGugZTWDl133LIEifh0bsb+MxgcG4ihCNUPbSoQLxx5obtnfBAXDI2B2Q=

notifications:
  email: false
